apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  {{- range $k, $v := .Values.hubTest.configmap }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
