image:
  repository: harbor.rnd.lanit.ru/public/hub-test
  tag: fix
  pullPolicy: Always
imagePullSecrets:
  - name: regcred
envVariables:
  ADBTEST_WATCH: "true"
  ADBTEST_HTTP_ADDR: ":8080"
  ADBTEST_DB: "/data/reports/hub-test.db"
  ADBTEST_APK: "/data/apk/ApiDemos-debug.apk"
  ADBTEST_HUB_NAMESPACE: "peer"
  ADBTEST_HUB_NS_SERVICE: "hub-test"
  ADBTEST_HUB_URL: "http://hub-server.peer.svc.cluster.local:8080"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
ingress:
  enabled: true
  className: nginx-internal
  hosts:
    - host: test.rrawww.ru
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: hub-test
              port:
                number: 8080
