image:
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

serviceAccount:
  create: false
  name: hub-test

envVariables:
  ADBTEST_WATCH: "true"
  ADBTEST_HTTP_ADDR: ":8080"
  ADBTEST_DB: "/data/reports/hub-test.db"
  ADBTEST_APK: "/data/apk/ApiDemos-debug.apk"
  ADBTEST_HUB_NAMESPACE: "peer"
  ADBTEST_HUB_NS_SERVICE: "hub-test"
  ADBTEST_HUB_URL: "http://hub-server.peer.svc.cluster.local:8080"
  TEST_IMAGE: "harbor.rnd.lanit.ru/public/hub-test-tests:${CI_COMMIT_REF_SLUG}"
  IOS_TEST_IMAGE: "harbor.rnd.lanit.ru/public/hub-test-tests-ios:${CI_COMMIT_REF_SLUG}"
  APPIUM_IMAGE: "dhub.rnd.lanit.ru/appium/appium:latest"

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

service:
  enabled: true
  port: 8080
  targetPort: http

pvc:
  enabled: true
  name: hub-test-data
  storageSize: 10Gi
  storageClassName: local-path
  accessModes: ReadWriteOnce

volumeMounts:
  - name: data
    mountPath: /data

volumes:
  - name: data
    persistentVolumeClaim:
      claimName: hub-test-data

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  className: nginx-internal
  hosts:
    - host: test.mfarm.rnd.lanit.ru
      paths:
        - path: /
          pathType: Prefix

pipeline: ${CI_PIPELINE_URL}
